### ISSUE TITLE
Mapping Couchbase documents to ElasticSearch types doesn't work 

### ISSUE THREAD

**Issue by varelasavela** [couchbaselabs/elasticsearch-transport-couchbase#100]
I tried to change the mapping from couchbaseDocument to my type (report) by two different ways and it still maps it to couchbaseDocument

way 1:
couchbase.typeSelector:
  org.elasticsearch.transport.couchbase.capi.RegexTypeSelector:
    - couchbase.typeSelector.documentTypesRegex.report: ^user.+$

way 2 :
couchbase.typeSelector:
  org.elasticsearch.transport.couchbase.capi.DefaultTypeSelector:
    couchbase.typeSelector.defaultDocumentType: report

Did I miss something ?

**Comment by baalthazaar1** [comment]
I share your pain.... I went through some frustrations when trying to do this for myself.
I haven't seen the syntax that you used listed anyway, but I think what you're trying to do is:

couchbase.typeSelector: org.elasticsearch.transport.couchbase.capi.RegexTypeSelector
couchbase.typeSelector.documentTypesRegex.report: ^user.+$

on two separate lines. Hope that works for you.

Cheers

**Comment by varelasavela** [comment]
Thx,
With 2 separated lines it works as expected
