### ISSUE TITLE
Cannot install plugin on ES 2.1.1

### ISSUE THREAD

**Issue by rostiar** [couchbaselabs/elasticsearch-transport-couchbase#107]
[root@ip-172-32-2-164 elasticsearch]# bin/plugin install https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/tag/2.1.2
-> Installing from https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/tag/2.1.2...
Trying https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/tag/2.1.2 ...
Downloading ..................DONE
Verifying https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/tag/2.1.2 checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by Branor** [comment]
Just released a version that supports ES 2.1.1, please take a look here: https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/tag/2.2.1
