### ISSUE TITLE
Access denied when trying to download 2.2.1 plugin 

### ISSUE THREAD

**Issue by Puzochacha** [couchbaselabs/elasticsearch-transport-couchbase#108]
I am trying to download package from link which you described in readme
http://packages.couchbase.com.s3.amazonaws.com/releases/elastic-search-adapter/2.2.1/elasticsearch-transport-couchbase-2.2.1.zip
But get access denied

**Comment by veacks** [comment]
Same here, 403 I can't install anymore the plugin

**Comment by Branor** [comment]
Sorry, readme was updated prematurely. Fixed the install instructions now.

**Comment by jcspino** [comment]
This appears to be an issue again, the link below gives me a 403 error. 

bin/plugin -i transport-couchbase -url http://packages.couchbase.com.s3.amazonaws.com/releases/elastic-search-adapter/2.1.2/elasticsearch-transport-couchbase-2.1.2.zip

Thanks,
Jonathan
