### ISSUE TITLE
Package 2.2.1.2 is not Available

### ISSUE THREAD

**Issue by miridfd** [couchbaselabs/elasticsearch-transport-couchbase#109]
The download link is broken:
https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/download/2.2.1.2/elasticsearch-transport-couchbase-2.2.1.2.zip.

Please get it back ASAP.

Thanks,

**Comment by Branor** [comment]
Fixed link. It's https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/download/v2.2.1.2/elasticsearch-transport-couchbase-2.2.1.2.zip
