### ISSUE TITLE
Question: Is replication from elastic to couchbase supported?

### ISSUE THREAD

**Issue by npow** [couchbaselabs/elasticsearch-transport-couchbase#112]
I just tried replicating _from_ elastic to couchdb (don't have couchbase at the moment), and nothing happened. Presumably this is because the `_changes` endpoint isn't returning anything. Is this supposed to work, or is only one-way replication supported?

**Comment by chester89** [comment]
I'm not sure this scenario is supported - the code is a Elasticsearch plugin that acts as if it were Couchbase node.

**Comment by WillGardella** [comment]
Correct, the Elasticsearch Transport Plugin is designed to write changes from Couchbase into Elasticsearch only and it has no provision to go the other way.

**Comment by npow** [comment]
Alright, thanks for the info.
