### ISSUE TITLE
How can I download ver 2.3.0?

### ISSUE THREAD

**Issue by orzilca** [couchbaselabs/elasticsearch-transport-couchbase#117]
I'm using latest stable version of ES (2.2.0) with the latest version of Kibana.

I see version 2.3.0 of transport-couchbase in the versions table but I no such releasse...

anyone?

**Comment by WillGardella** [comment]
That release hasn't been cut yet; @Branor just put it in as a placeholder. I put in a pull request to update that table to make it clear.

**Comment by peterhallen** [comment]
Any expectation on when 2.3.0 will be out?

**Comment by orzilca** [comment]
24b5ecd

**Comment by Branor** [comment]
Sorry folks, workig on it. :)

**Comment by dnault** [comment]
Just doing some housekeeping. If anyone arrives looking for 2.2.3.0, here's the download link:

https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/download/2.2.3.0/elasticsearch-transport-couchbase-2.2.3.0.zip
