### ISSUE TITLE
Download Plugin Version that Matches ES 2.2.0

### ISSUE THREAD

**Issue by miridfd** [couchbaselabs/elasticsearch-transport-couchbase#118]
Hello,

Please provide a download link to the plugin version which is compatible with ES 2.2.0.
If no such version exists, please let me know.

Thanks!!
Miri

**Comment by rostiar** [comment]
+1

**Comment by orzilca** [comment]
+1

**Comment by Branor** [comment]
Sorry folks, the 2.2.0 version in the readme was a placeholder. I should have made it clear (or removed it from the version marix). I'm working on a plugin version that supports ES 2.2.

**Comment by orzilca** [comment]
hey @Branor , any time estimation?

**Comment by Branor** [comment]
Can't commit to an exact date, but 2-3 weeks for a github release (here) and another week or two after that for Couchbase QA and an official release.

If anyone wants to take a look at the changes from 2.1 to 2.2 and contribute some code, I'll be happy to merge it. :)

**Comment by mcinnes01** [comment]
Hi @Branor 

Just wondered if there is any update? Also the compatibility table is a little miss leading it just caught me out, is there any chance this can be updated in the meantime?

Many thanks

Andy

**Comment by giladsw** [comment]
+1

**Comment by dnault** [comment]
Just doing some housekeeping. If anyone arrives looking for the download link for 2.2.2.0, here it is:

https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/download/2.2.2.0/elasticsearch-transport-couchbase-2.2.2.0.zip
