### ISSUE TITLE
Best upgrade strategy for Couchbse+XDCR+ES

### ISSUE THREAD

**Issue by nextofsearch** [couchbaselabs/elasticsearch-transport-couchbase#123]
Hi, I have a Couchbase v2.2 community edition cluster using XDCR to sync data to an Elasticsearch v1.0.1 cluster. I am wondering if I can do online upgrade to Couchbase v3.x by swap rebalance method while making less impact to the Elasticsearch cluster as possible. It seems upgrading v2.2 to v3 is complicated when XDCR is in place. Is there any step-by-step guide for this? Or does anyone have experience on this?

BTW, are the version numbers of Couchbase in the 'Version Compatibility' table in READEME.md ones of Enterprise Edition? Or the version numbers are compatible between Enterprise and Community edition?

**Comment by Branor** [comment]
The version numbers are the same for community and enterprise versions of Couchbase.

Regarding the upgarde process of Couchbase itself, it might be best to ask on the Couchbase forums. If you can disable replication while you're doing the upgrade, that would probably be best. If not, it should still work fine through the swap rebalances.
