### ISSUE TITLE
downloading plugin 2.3.1 - error message 

### ISSUE THREAD

**Issue by giladsw** [couchbaselabs/elasticsearch-transport-couchbase#124]
Hi David , 
I download the plugid and I got this error message.
Please advice.
Thanks 
G.O

C:\workspace\elasticsearch-2.3.1\bin>plugin install https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/download/2.2.3.1/elasticsearch-transport-couchbase-2.2.3.1.zip
-> Installing from https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/download/2.2.3.1/elasticsearch-transport-couchbase-2.2.3.1.zip...
Trying https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/download/2.2.3.1/elasticsearch-transport-couchbase-2.2.3.1.zip ...
Downloading ...........................................................................................................................................................................................................................................................................................................................DONE
Verifying https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/download/2.2.3.1/elasticsearch-transport-couchbase-2.2.3.1.zip checksums if available ...
Downloading .DONE
ERROR: Could not load plugin descriptor for existing plugin [elasticsearch-transport-couchbase-2.2.3.1.zip]. Was the plugin built before 2.0?

**Comment by Branor** [comment]
Are you still seeing this error? I've double-checked the download package, and it looks fine.

**Comment by giladsw** [comment]
Hi David ,
I've retry few weeks ago and it works.
Thanks


Best Regards ,
Gilad O. Swerdlow
DBA and IoT Analytics
