### ISSUE TITLE
Support for ES 2.3.2?

### ISSUE THREAD

**Issue by omerxx** [couchbaselabs/elasticsearch-transport-couchbase#128]
Hi David,

Any plan on releasing support for ES 2.3.2? 
Trying to follow the documentation I could not find a link to such version..

Thanks,
Omer

@Branor

**Comment by Branor** [comment]
Sure, here you go: https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/tag/2.2.3.2-update1
