### ISSUE TITLE
Cannot start ES due to Exception: org.elasticsearch.plugins.AbstractPlugin

### ISSUE THREAD

**Issue by omerxx** [couchbaselabs/elasticsearch-transport-couchbase#129]
Hi David,

Tried both ES 2.3.1 and 2.3.2, both with the matching plugin versions.
ES can't start, showing this exception:
`Likely root cause: java.lang.ClassNotFoundException: org.elasticsearch.plugins.AbstractPlugin`

When I remove the plugin, ES manages to start itself.

Any ideas?

**Comment by Branor** [comment]
OK, let's try to find the error cause. What jdk version are you using? And could you paste the rest of that exception, please?

**Comment by omerxx** [comment]
Hi David,
The machine's jdk hasn't changed from the previous ES:
![image](https://cloud.githubusercontent.com/assets/12237955/15806063/594ce334-2b43-11e6-9c17-8cb07839c7c1.png)

Here's the exception:
![image](https://cloud.githubusercontent.com/assets/12237955/15806058/32920512-2b43-11e6-9556-6051068c27f5.png)

**Comment by Branor** [comment]
Could you double-check the plugin and ES version, please? The plugin has no references to AbstractPlugin at all since version 2.2.x. Now does Elasticsearch itself as of 2.0+ for that matter.

**Comment by omerxx** [comment]
Yep, double checked, using the version you've linked me in #128:
`https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/download/2.2.3.2-update1/elasticsearch-transport-couchbase-2.2.3.2-update1.zip`
