### ISSUE TITLE
Double checking version compatibility

### ISSUE THREAD

**Issue by AndyMcInnes** [couchbaselabs/elasticsearch-transport-couchbase#131]
Hi,

I just wondered if you can confirm we are running compatible versions, we have gone off this from the wiki:

Plugin                           CB              ES
| 2.1                           |  2.5.x - 4.x  | 1.3.0 - 1.7.x   

But the Couchbase site says:

Couchbase 3.0.1
Elasticsearch Plugin 2.0.0
1.3.0 Compatible

We are running:

Couchbase 3.0.1
ES Plugin 2.1.1
ES 1.3.1

The reason I ask is because all of a sudden we are noticing the XDCR is failing to replicate with the following error in the CB logs:

[couchdb:error,2016-07-21T21:34:26.732,ns_1@Server.Local:<0.28819.427>:couch_log:error:44]Replicator, request POST to "http://Administrator:*****@192.168.169.144:9091/bucket_dev2013_2.0.2%2f308/_revs_diff" failed due to error {code,503}

Which seemed a little like the following maybe?

https://github.com/couchbaselabs/elasticsearch-transport-couchbase/issues/70

Or this: https://github.com/couchbaselabs/elasticsearch-transport-couchbase/issues/91

Many thanks

Andy

**Comment by Branor** [comment]
This does look like #70 that was fixed in 2.1.1. Could you double-check the jar version in the plugins/transport-couchbase directory? If that is indeed 2.1.1, could you post both the ES and CB logs around the time of the errors?

**Comment by AndyMcInnes** [comment]
Hi @Branor 

I upgrade to 2.1.1 and it all works a treat!

Many thanks

Andy
