### ISSUE TITLE
Elasticsearch log full of org.eclipse.jetty.http.HttpParser entries

### ISSUE THREAD

**Issue by VojtechMyslivec** [couchbaselabs/elasticsearch-transport-couchbase#133]
Hello,
I am trying to configure replication from *Couchbase cluster* to *Elasticsearch cluster* and connect *Kibana* to it.

I have 5 nodes (8 CPU, 12 GB RAM each) with *Couchbase 4.0 CE*, 2 nodes (2 CPU, 12 GB RAM) with *Elasticsearch 2.2.2* and *transport-couchbase plugin 2.2.2.2*.
EDIT: All hosts run up-to-date *Debian 8.5*, ES runs on *Oracle jdk 1.8.0u92*.

I have followed the instructions in [README.md](https://github.com/couchbaselabs/elasticsearch-transport-couchbase/blob/master/README.md) and created
 - an *Elasticsearch index* with following 
[kibana.json](https://github.com/couchbaselabs/elasticsearch-transport-couchbase/files/391310/kibana.json.txt) mapping
 - *1 Couchbase bucket* with cca 9 GB of data and 2 GB RAM quota per node.
 - XDRC cluster reference to elasticsearch cluster (first node)
 - *1 replication* from CB bucket to ES index

Everything seems to be fine: ES nodes starts to receiving data from CB cluster and I can see and filter the data from the index in Kibana interface.

Shortly after start - until all shards get to `STARTED` status - there are several exceptions in ES log, which IMHO is not relevant. Then there comes a lot of `INFO` log messages about successful import:

```
[2016-07-27 15:35:10,007][INFO ][transport.couchbase.capi ] [host2] bulk index succeeded after 1 tries
```

From which I can read the replication is running well. The problem starts after while when ES starts to spam log with similar messages like: 
```
[2016-07-27 03:29:11,913][WARN ][org.eclipse.jetty.http.HttpParser] 93A222356647265361964D3130531332C22776223A2...and 10000 bytes more ...5958637C5137744F5445354D693164ED5854630A7533E7469C3A0}{}
```
From now on, ES is producing more than 100 MB of these log messages per second.

I have googled a lot but not found anything relevant. These to issues are closest to my problem:
 - [Elasticsearch log entry explanation](https://stackoverflow.com/questions/33293770/elasticsearch-log-entry-explanation)
   - but my ES 2.2.2 use jetty.http v8.1.0
   - `base64 --decode` command with the above encoded data returns only binary bogus
   - there is also note about transport-couchbase plugin in comments
 - [Jetty HttpParser Full](https://stackoverflow.com/questions/14345872/jetty-httpparser-full)
   - similar issue, but from programmer point of view
   - I am just trying to configure mentioned tools (CB, ES+transport CB plugin)

Is there something I have configured wrong? How can I isolate the problem? When I delete the replication in CB, ES stops with logging this bogus messages.

**Comment by Branor** [comment]
Do you have the option to upgrade to the latest ES and plugin versions? The latest plugin version uses a newer Jetty. Regardless of that, could you provide more info about your data? In particular, approx number of documents and average document sizes?

For now, could you try lowering the XDCR batch count and size, to see if this is an HTTP parsing error from Jetty due to request size? (In the XDCR replication settings, pause the replication, lower the batch size and batch count to the minimum values, then resume the replication. See if problem with Jetty persists.)

**Comment by VojtechMyslivec** [comment]
Thanks a lot for your reply @Branor. 

Sadly, our developers need ES 2.2 for some reason.

I have 1 bucket with 7.1 M docs, 2 replicas 10 GB RAM quota in total. Disk Usage across the cluster is 21.6 GB (15.8 GB Data usage). Is this enough info?

I have just set the `XDCR Batch Size` from 1024 to 128 kB. I cannot set `XDCR Batch Count` to lower value than 500, which is the default.

I have also set another one ES index for our application with [application.json](https://github.com/couchbaselabs/elasticsearch-transport-couchbase/files/399618/application.json.txt) mapping (see the line 20) and another one XDRC replication from CB. Do you think it can be related to the problem?

**Comment by VojtechMyslivec** [comment]
After few hours, the log flood begins again. But now it spams only the master node' log only.

**Comment by VojtechMyslivec** [comment]
I have upgraded Couchbase to 4.1.0 CE, Elasticsearch to 2.3.5 and plugin to 2.2.3.5 last night.

XDRC is almost complete and the problem haven't appeared since. So I hope it's ok for now but I have set the `XDCR Batch Size` parameter to 16 kB and the replication is terribly slow. Do you suggest to increase the Batch Size back to default?

**Comment by VojtechMyslivec** [comment]
I can confirm that with _CB 4.1_ and _ES 2.3.5_, the default value 1024 `XDCR Batch Size` works fine.
