### ISSUE TITLE
WTF!? Configuration..

### ISSUE THREAD

**Issue by aLkRicha** [couchbaselabs/elasticsearch-transport-couchbase#136]
So, i have problem with configuration.

_couchbase  4.0.0-4051_
_elasticsearch 2.3.5_

i have documents in couchbase with **id** like **story_<slug>**
on http://localhost:9200/_template i have this template.
```
{
  couchbase: {
    order: 10,
    template: "story*",
    settings: {
      
    },
    mappings: {
      couchbaseDocument: {
        dynamic: "true",
        _source: {
          includes: [
            "meta.*"
          ]
        },
        dynamic_templates: [
          {
            all_strings_to_avoid_collisions: {
              mapping: {
                include_in_all: false,
                index: "not_analyzed",
                store: "no",
                analyzer: "whitespace",
                type: "string"
              },
              match: "*"
            }
          }
        ],
        properties: {
          doc: {
            properties: {
              type: {
                type: "string"
              }
            }
          },
          meta: {
            properties: {
              id: {
                analyzer: "whitespace",
                type: "string"
              }
            }
          }
        },
        _all: {
          enabled: false
        }
      },
      _default_: {
        _source: {
          includes: [
            "meta.*"
          ]
        },
        properties: {
          meta: {
            include_in_all: false,
            type: "object"
          }
        }
      }
    },
    aliases: {
      
    }
  }
}
```

so, i want to know how i can configure just to sync school documents, and don't sync couchbaseCheckpoint.. Thanks.

**Comment by Branor** [comment]
The couchbaseCheckpoint documents hold the replication state, so they are essential to the plugin and Couchbase replication functioning correctly. Removing them, either from the mappings or Elasticsearch, will break the replication. 

There are only 1025 of those documents created per replication (1024 vbucket states + 1 global state), so they won't really bother you very much, escept aesthetically.

**Comment by aLkRicha** [comment]
@Branor ok, but what about first question?

**Comment by Branor** [comment]
If you're using Couchbase Enterprise Edition, you can set up a regex filter expression on the XDCR replication itself. If you're using Community Edition, you can use the `couchbase.keyFilter` setting in the plugin to configure which documents to index and which to discard. Check the readme for the exact syntax.

**Comment by aLkRicha** [comment]
There is somewhere a good and complete example of the pattern for replication?
