### ISSUE TITLE
The latest plugin (2.2.4.0) is not compatible with Elasticsearch 2.4.1

### ISSUE THREAD

**Issue by nextofsearch** [couchbaselabs/elasticsearch-transport-couchbase#140]
Hi,

When I tried to install 2.2.4.0 from master branch, it says:

> Plugin [transport-couchbase] is incompatible with Elasticsearch [2.4.1]. Was designed for version [2.4.0]

Any plan to fix this?

**Comment by stakach** [comment]
Would be good if the plugin didn't throw errors for patch releases - maybe only display a warning instead.

**Comment by WillGardella** [comment]
This is correct. A new plugin version is required for 2.4.1. It's on the radar but there's no date for it yet.

**Comment by Branor** [comment]
The plugin versioning mechanism in ES 2.0 and later requires plugins to be specific to a particular release, including the minor version. This means that we have to build a new plugin package for each minor release of ES.
