### ISSUE TITLE
Support for ES 5.x

### ISSUE THREAD

**Issue by korczis** [couchbaselabs/elasticsearch-transport-couchbase#147]
Are there any plans to support ES 5.x ?

**Comment by korczis** [comment]
@mschoch @Branor can you, please, share your thoughts ?

**Comment by korczis** [comment]
What is needed to achieve ES 5.x compatibility?

**Comment by WillGardella** [comment]
Hi @korczis  - talked to @branor and 5.1 support is planned for Q1 2017. The reason it's taking a while is that ES removed an API that we formerly used to synchronize plugin instances, which we need to do to make sure vBuckets are mapped appropriately across the cluster. There's no replacement for that API and ES is not bringing it back, so we need to figure out how to move forward with the reduced functionality. This would probably mean that your cluster is created appropriately but would need to be restarted when you add or remove nodes to your cluster. There may be other impacts that are less obvious, too, but that's the major one.

**Comment by korczis** [comment]
Thank you for answer.

**Comment by Branor** [comment]
We now have a pre-release version of the plugin for ES 5.2.1 available here: https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/tag/v.2.5.2.1
It's fully functional, but hasn't made it through the full QA process at Couchbase yet.

**Comment by chenbekor** [comment]
@Branor what is the ETA on a final release for 2.5.x?
