### ISSUE TITLE
Elasticsearch Transport Couchbase for the 5.x versions

### ISSUE THREAD

**Issue by woltob** [couchbaselabs/elasticsearch-transport-couchbase#148]
Dear contributors,

I really love your couchbase transport plugin!
Since I couldn't get the alpha version for ES 5.x to work properly, I still use ES 2.x and thus would really love to see the plugin being released for 5.x as a production version.
Can you tell me when or if you're planning to finish the 5.x plugin?

Thank you very much!
Best regards,
woltob

**Comment by Branor** [comment]
We now have a pre-release version of the plugin for ES 5.2.1 available here: https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/tag/v.2.5.2.1
It's fully functional, but hasn't made it through the full QA process at Couchbase yet.
