### ISSUE TITLE
readme file problem

### ISSUE THREAD

**Issue by naderdl** [couchbaselabs/elasticsearch-transport-couchbase#162]
readme file on line 15 link is not ok please fix that:
bin/plugin install https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/download/v2.<ES_VERSION>/elasticsearch-transport-couchbase-2.<ES_VERSION>.zip
should change to :
bin/plugin install https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/download/2.<ES_VERSION>/elasticsearch-transport-couchbase-2.<ES_VERSION>.zip

**Comment by dnault** [comment]
Thanks! Fixed in 15fa2337066a36a0dbb443bb662bf1be5b65213c.
