### ISSUE TITLE
Update plugin for ES 5.4.3 and 5.5.0

### ISSUE THREAD

**Issue by solomon87** [couchbaselabs/elasticsearch-transport-couchbase#167]
Seems like the ES plugin is a few version behind. Will there be compatibility updates made for the latest versions?

**Comment by BLZB0B** [comment]
+1

**Comment by BLZB0B** [comment]
I've created a pull request to fix this

**Comment by BLZB0B** [comment]
you can install the current version and edit the plugin-descriptor.properties file in the plug in folder - just stop elastic, update the elasticsearch version number in the above file and restart elastic.

**Comment by dnault** [comment]
First off, apologies for the inconvenience and the belated response.

The soon-to-be-released version 3.0.0 of the plugin will be available for every ES version from 2.2.0 to 5.6.4.

**Comment by dnault** [comment]
Version 3.0.0 has been [released](https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases) and is available for all ES versions from 2.2.0 to 5.6.4.
