### ISSUE TITLE
Wrong link for 5.x install

### ISSUE THREAD

**Issue by tonipepperoniuk** [couchbaselabs/elasticsearch-transport-couchbase#169]
The guide states that the install link for 5.x should be:

bin/elasticsearch-plugin install https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/download/v2.<ES_VERSION>/elasticsearch-transport-couchbase-2.<ES_VERSION>.zip

Whereas it should be:

bin/elasticsearch-plugin install https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/download/2.<ES_VERSION>/elasticsearch-transport-couchbase-2.<ES_VERSION>.zip

Removing the 'v' after /download/

**Comment by dnault** [comment]
Thanks! Fixed in 15fa2337066a36a0dbb443bb662bf1be5b65213c
