### ISSUE TITLE
support question

### ISSUE THREAD

**Issue by naderdl** [couchbaselabs/elasticsearch-transport-couchbase#172]
hi is there any support for elasticsearch v 2.4.6?
I'm brew on Mac and there are only elasticsearch 2.4.6 and 5.5.2?
is there any support for them?

**Comment by dnault** [comment]
First off, apologies for the inconvenience, and the belated response.

The soon-to-be-released version 3.0.0 of the plugin will be available for every ES version from 2.2.0 to 5.6.4. 

By the way, the Elasticsearch distributions are cross-platform, so brew isn't strictly necessary; all you need is Java.

Cheers,
David

**Comment by dnault** [comment]
Version 3.0.0 has been [released](https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases) and is available for all ES versions from 2.2.0 to 5.6.4.
