### ISSUE TITLE
ElasticSearch and Couchbase Supported Version Query

### ISSUE THREAD

**Issue by mackie1311** [couchbaselabs/elasticsearch-transport-couchbase#187]
Hi,

This is a question more than an issue but wondered if there is a plan to have a connector between ElasticSearch 6.x and latest Couchbase? Your table only shows support for 5.x so not sure if there are plans to get a new plugin line out for 6.x version of ES.
+---------------------------------------------------------------------+
|  Plugin Line    |  Git Branch     |  Elasticsearch  |  Couchbase    |
+---------------------------------------------------------------------+
| cypress         | release/cypress | 5.x             |  4.x - 5.x    |
+---------------------------------------------------------------------+    
| alder           | release/alder   | 2.2.0 - 2.4.6   |  4.x - 5.x    |
+---------------------------------------------------------------------+

Thanks,

**Comment by dnault** [comment]
Hi Mackie,

Yes, support for ES 6.x is planned. See https://github.com/couchbaselabs/elasticsearch-transport-couchbase/issues/180

Thanks,
David
