### ISSUE TITLE
java.lang.AutoCloseable not found

### ISSUE THREAD

**Issue by ltamrazov** [couchbaselabs/elasticsearch-transport-couchbase#43]
Hi, 

I am trying to build this project, but I am getting the following error when I run mvn package in elasticsearch-transport-couchbase folder:

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/Levon/GoogleDrive/BFM/Dev/custom-plugins/transport-couchbase/elasticsearch-transport-couchbase-master/src/main/java/org/elasticsearch/transport/couchbase/capi/ElasticSearchCAPIBehavior.java:[115,58] cannot access java.lang.AutoCloseable
class file for java.lang.AutoCloseable not found
        IndicesExistsRequestBuilder existsBuilder = client.admin().indices().prepareExists(index);
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.694 s
[INFO] Finished at: 2014-08-25T12:39:51-04:00
[INFO] Final Memory: 15M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project elasticsearch-transport-couchbase: Compilation failure
[ERROR] /Users/Levon/GoogleDrive/BFM/Dev/custom-plugins/transport-couchbase/elasticsearch-transport-couchbase-master/src/main/java/org/elasticsearch/transport/couchbase/capi/ElasticSearchCAPIBehavior.java:[115,58] cannot access java.lang.AutoCloseable
[ERROR] class file for java.lang.AutoCloseable not found
[ERROR] IndicesExistsRequestBuilder existsBuilder = client.admin().indices().prepareExists(index);
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

My directory structure is as follows:
root/
    couchbase-capi-server-master
    elasticsearch-transport-couchbase-master

Not sure if this is relevant, but I've download the latest version of elasticsearch and it remains in:
usr/local/elasticsearch-1.3.2

I've tried to build this the way I did previous versions:
1. run mvn install inside couchbase-capi-server-master (builds successfully)
2. run mvn package inside elasticsearch-transport-couchbase-master (gets error)

This has successfully worked int he past. Not sure where to go from here. Am I building it wrong or is this an issue? 

Thank you,

**Comment by ajaykeshri** [comment]
Even I set java 1.7/1.8 error is same,  any other setting require, there is no problem for build and run but its show red line there.

Thanks

**Comment by cmrishi1990** [comment]
Thanks
