### ISSUE TITLE
mapping of parent/child relationship from couchbase to elasticsearch

### ISSUE THREAD

**Issue by awkysam** [couchbaselabs/elasticsearch-transport-couchbase#44]
if there is a parent/child mapping in Elasticsearch how should be the elasticsearch-transport-couchbase-1.3.0 configured so that parent information is collected from couchbase documents.
Example..
want to store paragraphs of a document in couchbase and index it in ElasticSearch and maintain document name in parent field.

one thing we tried is try to set parent manually
"builder.setParent("1");" in ElasticSearchCouchbaseBehavior.java file in storeUUID function
but it fails.

Please let us know if this is possible or some configuration needs to be done
Have seen some modifications on CouchbaseCAPITransportImpl.java file but how to set in configurations.

**Comment by it-vegard** [comment]
Any idea when we can expect the release with dynamic types (milestone 2.1.0, apparently)?
On the milestones page it says it is "Past due date by about a month".

Dynamic types would solve the only problems I have with this plugin, so I am looking forward to trying it out.

**Comment by Branor** [comment]
Added in v2.1.1 - you can get the RC here: https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/tag/2.1.1-RC
