### ISSUE TITLE
incremental replication to ES

### ISSUE THREAD

**Issue by behrad** [couchbaselabs/elasticsearch-transport-couchbase#55]
When using active/continuous replication, couchbase TTLs (doc deletions) affects ES, so ES docs are deleted despite https://github.com/couchbaselabs/elasticsearch-transport-couchbase#couchbase-document-expiration

if I have a couchbase TTL of 1 day, and I want a month of my data in my ES (I want to search in large, but no need to store my huge daily data in couchbase), how should I get to this? or, Where am I thinking wrong about this?

**Comment by Branor** [comment]
The upcoming version (2.1.0) includes this option. You can get a preview build here: https://drone.io/github.com/Branor/elasticsearch-transport-couchbase/files/target/releases/elasticsearch-transport-couchbase-2.1.0-SNAPSHOT.zip
An updated readme with all the configuration options: https://github.com/Branor/elasticsearch-transport-couchbase/blob/master/README.md

**Comment by Branor** [comment]
Added in 2.1.1

**Comment by behrad** [comment]
thank you :+1:
