### ISSUE TITLE
block document expiration propagation to ES

### ISSUE THREAD

**Issue by chenbekor** [couchbaselabs/elasticsearch-transport-couchbase#60]
when saving json docs in CB I'm setting the expiration to X days.  Those docs are synced to ES via XDCR. after X days, the docs are deleted from CB due to TTL and they are also deleted from ES.  What I need is a way to leave those docs in ES. Is it possible?

**Comment by mschoch** [comment]
This is currently not possible.  The XDCR protocol was designed for replication, so to keep both sides in sync it propagates expired documents as deletes.

The only way to accomplish this would be to modify the source to ignore all deletes.  Note, this would ignore all deletes not just expired documents, as there is no way to distinguish these in the XDCR protocol.

**Comment by chenbekor** [comment]
interesting. by change the source I hope you mean transport plugin and not xdcr :)  if so can you please give me a hint where in the source to loolk for the modification? 

for my use case it is an append only system so  I don't mind ignoring all deletes.

**Comment by mschoch** [comment]
It might be as simple as commenting out these lines:

https://github.com/couchbaselabs/elasticsearch-transport-couchbase/blob/master/src/main/java/org/elasticsearch/transport/couchbase/capi/ElasticSearchCAPIBehavior.java#L356-L357

**Comment by chenbekor** [comment]
super! and if I want to exclude the lines only for specific buckets how would you recommend doing that and how would the code change to reflect that?

**Comment by mschoch** [comment]
The name of the elasticsearch index is in the variable "database".  But making it configurable would be a lot more work.  The configuration is parsed by another class, and you'd have to pass in some datastructure to the constructor.  You can take a look at how the existing options are configured here: https://github.com/couchbaselabs/elasticsearch-transport-couchbase/blob/master/src/main/java/org/elasticsearch/transport/couchbase/capi/CouchbaseCAPITransportImpl.java#L87-L102

**Comment by chenbekor** [comment]
@Branor can you please inspect this request - I will try to follow Marty's advice as discussed here but I would really like to see this feature pushed into mainstream. How do you suggest we do that? would a Pull Request work?

**Comment by chenbekor** [comment]
thanks for the help guys - I finalized and tested the modifications.
please review pull request https://github.com/couchbaselabs/elasticsearch-transport-couchbase/pull/62

**Comment by Branor** [comment]
@chenbekor Merged the PR into the master. I'll merge my own changes tomorrow, test and build a new version of the binaries.

**Comment by chenbekor** [comment]
@Branor  what's the status of a new binary? we need an ETA on this otherwise we will have to go for a SNAPSHOT release which is not something we want in PROD.

Also - support for ES1.4 is crucial. BTW - Thanks for approving our PR !!

**Comment by Branor** [comment]
@chenbekor You can try out a test build here: https://drone.io/github.com/Branor/elasticsearch-transport-couchbase/files/target/releases/elasticsearch-transport-couchbase-2.1.0-SNAPSHOT.zip
An updated readme with all the configuration options: https://github.com/Branor/elasticsearch-transport-couchbase/blob/master/README.md
It will be available as soon as it's through QA.

**Comment by Branor** [comment]
Added in 2.1.1
