### ISSUE TITLE
Support RegEx groups in mapping to ES types

### ISSUE THREAD

**Issue by synhershko** [couchbaselabs/elasticsearch-transport-couchbase#64]
Taking the example from the documentation:

`couchbase.documentTypes.review: ^review-(\d)+$`

Can potentially be written as:

`couchbase.documentTypes.$1: ^(\w+)-(\d)+$`

And by that allowing creating types based on a pattern instead of explicitly defining many ES types in places where its required - and there is a pattern in document IDs.

**Comment by shivangshah** [comment]
If I got this right, are you requesting for dynamic creation of document types based on some regex inside document Ids ? if so, +1 to the above request. That might just help designing our multi-tenancy issue I mentioned here: http://stackoverflow.com/questions/28314272/couchbase-elastic-search-plugin-with-multi-tenancy/28322772

**Comment by Branor** [comment]
The upcoming version (2.1.0) includes this feature. You can try a test build for yourself: https://drone.io/github.com/Branor/elasticsearch-transport-couchbase/files/target/releases/elasticsearch-transport-couchbase-2.1.0-SNAPSHOT.zip
An updated readme with all the configuration options: https://github.com/Branor/elasticsearch-transport-couchbase/blob/master/README.md

**Comment by Branor** [comment]
Latest RC of v2.1.1 supports regex groups in type mapping. RC here: https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/tag/2.1.1-RC
