### ISSUE TITLE
support elasticsearch 1.4

### ISSUE THREAD

**Issue by android-programmer** [couchbaselabs/elasticsearch-transport-couchbase#65]
Elasticsearch 1.4 has more functionalities (e.g filters aggregations, scripted metric aggregation) than 1.3

**Comment by corbinu** [comment]
+1

**Comment by chenbekor** [comment]
+1

**Comment by tshak** [comment]
+1

**Comment by android-programmer** [comment]
also kibana 4 only supports elasticsearch 1.4

**Comment by Branor** [comment]
Hi folks, the upcoming version (2.1.0) will support ES 1.3.0 to 1.4.3. It's currently in QA but you can try a snapshot build for yourselves here: https://drone.io/github.com/Branor/elasticsearch-transport-couchbase/files/target/releases/elasticsearch-transport-couchbase-2.1.0-SNAPSHOT.zip
An updated readme with all the configuration options: https://github.com/Branor/elasticsearch-transport-couchbase/blob/master/README.md

**Comment by corbinu** [comment]
Hey thanks much @Branor .... As it seems to me there is many who use this plugin is there anyway we could help build a test suite for this project so that even if there is not official couchbase support for a newer version of elasticsearch we could build, test and debug? 

Just seems like a lot of people that might be happy to contribute to the project especially if it helps keep tow with Elasticsearch's very fast release cycle.

**Comment by Branor** [comment]
I'd be very happy to have someone help build a test suite. The easiest way for you to start would be to just fork the repo and add some tests, then submit a pull request.

**Comment by chenbekor** [comment]
hey @Branor where do we stand with a final release that supports ES 1.4.x? is there any major bug holding you from releasing this? maybe we can help?

**Comment by Branor** [comment]
The next version is going through QA now, it will be released within the next two weeks or so.

**Comment by priteshpatel15** [comment]
Hi @Branor, is this plugin still scheduled to be released?  I've already run the old plugin with Elastic 1.4 and it seems to work just fine for that usecase.  I will be implementing a more complex use case this coming week with the latest Couchbase and Latest Elastic. Just wanted to know the timing of release.  I could be your first test of it.  I will be doing this on Monday.

**Comment by allanvarrette** [comment]
Does this snapshot support 1.44?   Kibana only supports Elasticsearch 1.44....

**Comment by Branor** [comment]
v2.1.1 supports all ES versions up to 1.5.2 (latest right now) - check out the RC here: https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/tag/2.1.1-RC
