### ISSUE TITLE
Create test suite

### ISSUE THREAD

**Issue by corbinu** [couchbaselabs/elasticsearch-transport-couchbase#71]
Figured this should be a new issue from #65

I will fork and try setting up something basic at least.

**Comment by Branor** [comment]
That's awesome, thank you!

**Comment by dnault** [comment]
Just doing housekeeping on inactive issues. Okay to close this?

**Comment by corbinu** [comment]
Ya I stopped using this a while back so if nobody else has an interest just close for now
