### ISSUE TITLE
ignoreDeletes stopped working

### ISSUE THREAD

**Issue by chenbekor** [couchbaselabs/elasticsearch-transport-couchbase#75]
@Branor please review again ticket #74  - it has new comments related to regression in ignoreDelete. I will greatly appreciate it if you can have a look.

**Comment by chenbekor** [comment]
we are trying to debug it - but we are not sure we are using the latest. for example - @Branor said that the current flag for ignore deletes is called couchbase.ignoreDeletes instead of  couchbase.ignore.delete   BUT in the code we cannot see a reflection of this. So where can we gran the code of the SNAPSHOT release in order to debug this issue?

**Comment by Branor** [comment]
Take a look at the latest RC: https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/tag/2.1.1-RC
