### ISSUE TITLE
Support elasticsearch 1.5

### ISSUE THREAD

**Issue by JordyMoos** [couchbaselabs/elasticsearch-transport-couchbase#78]
Elasticsearch 1.5 is out. Can it be supported?

**Comment by chenbekor** [comment]
+1

Also - @Branor I believe that the latest snapshot is not committed to git. You only provided a zip version. Is there any chance that you let us have access to latest code?

**Comment by DemonTPx** [comment]
+1

**Comment by android-programmer** [comment]
+99

**Comment by android-programmer** [comment]
we have been waiting for 1.4 but now     itsalready 1.5 it says they are under QA a few months ago, but still nothing happen

**Comment by majcher** [comment]
+1

**Comment by Branor** [comment]
RC of v2.1.1 is out, which includes support of all ES versions up to 1.5.2: https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/tag/2.1.1-RC

**Comment by JordyMoos** [comment]
Thanks a lot @Branor
