### ISSUE TITLE
Filter on replication of data from couchbase to Elasticsearch

### ISSUE THREAD

**Issue by ddeepak4u** [couchbaselabs/elasticsearch-transport-couchbase#8]
A filter option should be there on keys or patterns of couchbase data to replicate into Elasticsearch while setting up the replication.

There are use cases when you don't need to replicate  whole bucket. Instead you need  only keys following certain patterns to be replicated in ES.

**Comment by Branor** [comment]
I've added an option to filter documents by their ID at the destination. You can try a preview release that includes this feature here: https://github.com/Branor/elasticsearch-transport-couchbase/releases/tag/v2.1.0-SNAPSHOT

**Comment by ali2007** [comment]
i will tried this night .
Nice for your reactivite .
 Le 14 févr. 2015 11:05, "David Ostrovsky" <notifications@github.com> a
écrit :

**Comment by ali2007** [comment]
sorry Branor  i config  es in es.yml like this:
couchbase.keyFilter: org.elasticsearch.transport.couchbase.capi.RegexKeyFilter
couchbase.keyFilterType: exclude
couchbase.keyFilters.filter1:  ^temp.*$
and i put document with ids like : temp:1234
but es replicate this docs

**Comment by ali2007** [comment]
sorry Branor i config es in es.yml like this:
couchbase.keyFilter:
org.elasticsearch.transport.couchbase.capi.RegexKeyFilter
couchbase.keyFilterType: exclude
couchbase.keyFilters.filter1: ^temp.*$
and i put document with ids like : temp:1234
but es replicate this docs

2015-02-14 14:01 GMT+00:00 jamai Ali <abdaz140684@gmail.com>:

**Comment by ali2007** [comment]
please im wating for your response 
thinks

**Comment by ali2007** [comment]
im watting for your response

**Comment by Branor** [comment]
@ali2007 I'll look into it.

**Comment by ali2007** [comment]
Ok it s verry nice there is a long time and im loking for this solution .
Im not verry good in java i work with this architecture.
Db:couchbase
Search engine: es
Server:node js
Sow js
Le 22 févr. 2015 10:31, "David Ostrovsky" <notifications@github.com> a
écrit :

**Comment by Branor** [comment]
Fixed in v2.1.1

**Comment by ali2007** [comment]
david your gmail please


2015-08-13 19:22 GMT+01:00 David Ostrovsky <notifications@github.com>:

**Comment by mashhur** [comment]
Hi there~
I am facing very strange situation that (using CB 4.5.1 enterprise edition) XDCR filter sometimes work sometimes doesn't. Even match test is not working too, you can see in attachment pic.
Please help me to analyze what is wrong with it.

![screen shot 2018-05-14 at 11 31 58 am](https://user-images.githubusercontent.com/6016642/39975621-ad580abc-576a-11e8-8ff9-f6b70475bcae.png)

**Comment by dnault** [comment]
@mashhur As far as I know, the Elasticsearch connector does not play a role in XDCR filtering (the connector just receives whatever documents are sent by Couchbase Server).

I'd recommend posting over on the [Couchbase Server forum](https://forums.couchbase.com/c/couchbase-server), and/or since you're an Enterprise customer, raising a support issue.
