### ISSUE TITLE
XDCR sync is lost without errors

### ISSUE THREAD

**Issue by bigShai** [couchbaselabs/elasticsearch-transport-couchbase#83]
Working on Couchbase 2.2, ElasticSearch 0.90.5 and Plugin 1.2.0.

After X amount of time (few hours) the bucket and the index are no longer synced.
There is no error on Couchbase logs and no error in the elasticsearch logs.

There is no indication that the XDCR isn't working properly but the docs on CB are not being updated to the ES index.

**Comment by Branor** [comment]
Those are all pretty old versions of Couchbase, ElasticSearch and the plugin. Are you able to upgrade ES and the plugin, at the very least? There were multiple issues related to replication stability that were fixed between versions 1.2.0 and 2.1.1.

You can get the RC of the latest version here: https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/tag/2.1.1-RC
