### ISSUE TITLE
way to index full document

### ISSUE THREAD

**Issue by SiddiqueAhmad** [couchbaselabs/elasticsearch-transport-couchbase#89]
is there any option available, i want to index full document from couchbase to elastich search

**Comment by Branor** [comment]
Sorry, could you please explain a little further - what is it you're trying to do?

**Comment by MuhammadAmmad** [comment]
want to store full document in elastic search, not just its meta data any option?

**Comment by Branor** [comment]
In the ES template, add "*.doc" to _source :["*.meta"]. Then delete and recreate the index.
