### ISSUE TITLE
Attention - Version 2 replication is disallowed. Remote cluster has nodes with versions less than 2.2.

### ISSUE THREAD

**Issue by davidsaliba** [couchbaselabs/elasticsearch-transport-couchbase#90]
Hi,
I just tried to install the ETC (elastic Transpost Couchbase) plugin on my ES cluster.
ES info
  "version" : {
    "number" : "1.4.2",
    "build_hash" : "927caff6f05403e936c20bf4529f144f0c89fd8c",
    "build_timestamp" : "2014-12-16T14:11:12Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.2"
  },

Tried to setup XDCR from Couchbase 

Version: 3.0.1 Community Edition (build-1444)

and I used : 

bin/plugin -install transport-couchbase -url https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/download/2.1.1-RC/elasticsearch-transport-couchbase-2.1.1-SNAPSHOT.zip

I am getting this in CB when trying to configue the XDCR

Attention - Version 2 replication is disallowed. Remote cluster has nodes with versions less than 2.2.

I followed the : 

|  Plugin                       |  Couchbase    | ElasticSearch    |
+------------------------------------------------------------------+
| master                        |  3.x, 2.5.x   | 1.3.0 - 1.5.2    |
+------------------------------------------------------------------+
| 2.1                           |  3.x, 2.5.x   | 1.3.0 - 1.5.2    |

Versioning guideline any hints please on how to get this working or where to get a version that actually works ?

**Comment by mouchar** [comment]
Did you set protocol to Version 1?

> If you are using Couchbase Server 2.2 or later, click Advanced settings and change the XDCR Protocol setting to Version 1

See https://github.com/couchbaselabs/elasticsearch-transport-couchbase#usage

**Comment by davidsaliba** [comment]
------ >   Advanced settings and change the XDCR Protocol setting to Version 1  <------------

Starting Data Transfer

Press the button labeled "Create Replication"
Select the bucket from source cluster you wish to send to ElasticSearch
Next select the cluster you defined in step 4.
Type in the name of the ElasticSearch index you wish to store the data in. This index must already exist.
If you are using Couchbase Server 2.2 or later, click Advanced settings and change the XDCR Protocol setting to Version 1


from (https://github.com/couchbaselabs/elasticsearch-transport-couchbase)
