### ISSUE TITLE
Replication does not occur, logs aren't telling much

### ISSUE THREAD

**Issue by Mayhem93** [couchbaselabs/elasticsearch-transport-couchbase#91]
Hello

Here's what I'm using before I get started:
- **Couchbase Server**: 3.0.1 Community Edition
- **ElasticSearch**: 1.5.4
- **ElasticSearch Transport Plugin**: 2.1.1 (latest)

I've managed to get this work some months ago, but I had to delete the replication (and the index). I follow the steps to install the plugin (install plugin + insert template into elastic). I create the replication on the couchbase server (default settings, Version 1 protocol).

And here is when it gets weird: i get like 1000 couchbase checkpoints and only ~40-50 objects from it. I pause the replication and resume it (from de couchbase admin interface). Another 50 objects are added. I keep doing that until I get all of them (which aren't many).

New/updated/deleted items are not replicated anymore. Only the times that were there when I started the replication get copied into elastic.

**xdcr_errors.log** - doesn't show anything
**xdcr.log** - http://pastebin.com/cd3zeUan
**elasticsearch.log** - http://pastebin.com/Kj4vr3sn

ElasticSearch logs scream when he finds some keys containing binary (or just a simple integer) data. But as far as I know he can handle it (I don't need those keys anyway).

**Comment by Branor** [comment]
Hi Mayhem93,

Could you please try setting the log level for the plugin to TRACE and upload the ES log again? Add "logger.transport.couchbase.capi: TRACE" in your logger.yml)

**Comment by Amit-A** [comment]
I'm seeing the same issue: ~1K couchbaseCheckpoints and only a few couchbaseDocuments. Every time I pause and resume, a few more documents get synced. 

Noticed this in xdcr_errors.log:
[xdcr:error,2015-08-29T21:33:40.311,ns_1@10.0.0.5:<0.32411.1>:xdc_vbucket_rep:terminate:489]Replication (CAPI mode) `42a755ead429328f8e48729973e82937/default/default` (`def$
                     "http://Administrator:*****@10.0.0.63:9091/default%2f565/_bulk_docs",
                     {error,{code,500}}}

**Comment by chester89** [comment]
@Mayhem93 did you try latest 2.1.1 version of the plugin or are you using RC? 2.1.1 was released 4-5 days ago

**Comment by Branor** [comment]
@Amit-A,

Hi Amit, could you please try running the plugin with log level set to TRACE and upload the result? (See original post.)

**Comment by Mayhem93** [comment]
@Branor 

Sorry for the *really* delayed reply.

Here's the log, I paused the replication and resumed it; this is what the logger says after doing so. (installed v2.1.1 plugin, non-RC). Same symptoms: only a few documents get replicated per pause/resume cycle.

http://pastebin.com/ZwUdDcK8

**Comment by propulkit** [comment]
Hi Guys,
Any Update on it ?

**Comment by propulkit** [comment]
@Mayhem93 Did you discover anything more on same ?

**Comment by Mayhem93** [comment]
No, I haven't used CB with ES anymore.

**Comment by propulkit** [comment]
@Mayhem93 Thanks for quick revert.

@Branor Do you like to share some thoughts.

**Comment by dnault** [comment]
@Mayhem93 @propulkit Okay to close the issue, or is there value in further investigation?

For anyone running into issues with this particular combination of software versions, my first recommendation would be upgrade to more recent versions of Couchbase and ES if possible.

**Comment by Mayhem93** [comment]
It can be safely closed imo
