### ISSUE TITLE
Missing artifact com.couchbase:couchbase-capi-server:jar:1.3.0

### ISSUE THREAD

**Issue by MuhammadAmmad** [couchbaselabs/elasticsearch-transport-couchbase#93]
<dependency>
			<groupId>com.couchbase</groupId>
			<artifactId>couchbase-capi-server</artifactId>
			<version>1.3.0</version>
		</dependency>
maven not adding dependency in eclipse.

**Comment by Branor** [comment]
Are you trying to build the plugin? If so, you'll have to clone https://github.com/couchbaselabs/couchbase-capi-server and do "mvn install" on that project first. It isn't in the official Maven repositories, so you have to actually get it manually.

**Comment by MuhammadAmmad** [comment]
Thanks

**Comment by MuhammadAmmad** [comment]
Sir can u plz explain this
https://github.com/couchbaselabs/elasticsearch-transport-couchbase/issues/89
