### ISSUE TITLE
ETA for supporting ElasticSearch 1.6 and 1.7

### ISSUE THREAD

**Issue by chester89** [couchbaselabs/elasticsearch-transport-couchbase#94]
Hello, we're currently thinking of upgrading our infrastructure and would like to use plugin with Elasticsearch 1.7. Any plans to support it? If so, do you have any estimation for it?

**Comment by voyagersm** [comment]
+1

**Comment by Branor** [comment]
1.7.x support is already in 2.1.1. :)
