### ISSUE TITLE
CAPI log on ES side complains about lookup that does not even exist in CB bucket.

### ISSUE THREAD

**Issue by rajeshetty** [couchbaselabs/elasticsearch-transport-couchbase#95]
I used to have all the  k/v lookups including following one (pu:bbnsgr4mrjceprbcyhn18q) in our main bucket and we moved all the lookup data  it to a dedicated lookups bucket and deleted it from main bucket. Now when I redo ES index and XDCR between CB and ES I still see following error.

[2015-09-01 15:36:56,219][ERROR][transport.couchbase.capi ] [Lady Mandarin] Unable to parse decoded base64 data as JSON, indexing stub for id: pu:bbnsgr4mrjceprbcyhn18q
[2015-09-01 15:36:56,219][ERROR][transport.couchbase.capi ] [Lady Mandarin] Body was:  Parse error was: java.io.EOFException: No content to map to Object due to end of input

Where is it getting above data from anyways, because these lookups no longer exist in the bucket thats being XDCR'd to ES and ES index itself is also completely rebuild .

Any idea?

**Comment by rajeshetty** [comment]
Im on CB 3.0.3, ES 1.6.0 and CB-ES 2.0 plugin version

**Comment by Branor** [comment]
My guess would be that XDCR is sending tombstones for deleted documents (to let the target cluster know that they've been deleted) - and the plugin can't parse that. I'll need to code around that. For now, you should be able to ignore the errors and continue.
