### ISSUE TITLE
ClassNotFoundException[org.elasticsearch.transport.couchbase.capi.DelimiterTypeSelector]

### ISSUE THREAD

**Issue by florianritzel** [couchbaselabs/elasticsearch-transport-couchbase#98]
I am using Version: Couchbase 4.0.0-4047 Community Edition (build-4047).
I am using elasticsearch-transport-couchbase-2.0.0 with Elasticsearch 1.4.4.

When I configure the DelimiterTypeSelector as the typeSelector and restart Elasticsearch, I get this error:

```
[2015-09-12 14:03:03,717][ERROR][bootstrap ] {1.4.4}: Initialization Failed ...
1) NoClassSettingsException[Failed to load class setting [couchbase.typeSelector] with value [org.elasticsearch.transport.couchbase.capi.DelimiterTypeSelector]]
ClassNotFoundException[org.elasticsearch.transport.couchbase.capi.DelimiterTypeSelector]
```

In comparison using the RegexTypeSelector class throws no such error.

**Comment by WillGardella** [comment]
Hi Florian - 
Couchbase Server 4.0 is not compatible with Elasticsearch Plugin 2.0 or the newer version of the plugin, 2.1.  Note that we're currently working on support for Couchbase Server 4, and although most things seem to work, there is one known issue that can result in high CPU usage ([MB-16244](https://issues.couchbase.com/browse/MB-16244)). I will go ahead and see if I can recreate that issue on my local system using Couchbase Server 4.0 Enterprise Edition and will post back later.
-Will
