### ISSUE TITLE
ElasticsearchParseException[Failed to derive xcontent]

### ISSUE THREAD

**Issue by clakech** [couchbaselabs/elasticsearch-transport-couchbase#99]
Hi,

Using this plugin in version 2.1.1 + ES 1.7.1 I face an error following this installation guide: http://developer.couchbase.com/documentation/server/4.0/connectors/elasticsearch-2.1/install-intro.html

```
curl -X PUT http://localhost:9200/_template/couchbase -d /elasticsearch/plugins/transport-couchbase/couchbase_template.json 

=>

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   145  100    79  100    66   1809   1511 --:--:-- --:--:-- --:--:--  1837
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

=>
{"error":"ElasticsearchParseException[Failed to derive xcontent]","status":400}
```

any idea ?

**Comment by atom992** [comment]
It's works fine in my machine with plugin in version 2.1.1 + ES 1.7.1 I.
you can change the log config to debug, and check the elasticsearch.log.
the log config:
<ES_HOME>/config/logging.yml
for example, change
es.logger.level: INFO
to
es.logger.level: DEBUG

the log should be:
<ES_HOME>/logs/elasticsearch.log

**Comment by clakech** [comment]
Thanks for your answer,

I setup log level to DEBUG

but there is not any log in ES logs... just the exact same error:

```
curl -X PUT http://localhost:9200/_template/couchbase -d /elasticsearch/plugins/transport-couchbase/couchbase_template.json
{"error":"ElasticsearchParseException[Failed to derive xcontent]","status":400}
```

**Comment by clakech** [comment]
with ES 1.5.2 here is the error:

```json
{"error":"ElasticsearchParseException[Failed to derive xcontent from org.elasticsearch.common.bytes.ChannelBufferBytesReference@550c7219]","status":400}
```

**Comment by atom992** [comment]
the ES cluster have no index before you define template?
I have a empty ES cluster, and have no index  before I define the template.
what the result of
curl -X GET http://localhost:9200/_template

**Comment by clakech** [comment]
yes, the ES is a brand new ES cluster with nothing inside at all:

```
curl -X GET http://localhost:9200/_template

=>

{ }
```

**Comment by clakech** [comment]
oh!

switching from:
```
curl -X PUT http://localhost:9200/_template/couchbase -d /elasticsearch/plugins/transport-couchbase/couchbase_template.json
```
to:

```
cd /elasticsearch
curl -X PUT http://localhost:9200/_template/couchbase -d @plugins/transport-couchbase/couchbase_template.json
```

save my day.

Seems like this '@' character is useful ^^

**Comment by naisanza** [comment]
@clakech What does the '@' character do to make it work for you?

**Comment by clakech** [comment]
@naisanza I don't know, with the @ it works, without the @ it doesn't work... found this tip somewhere on the dark web ^^ (in a deep forum)

**Comment by bkdonline** [comment]
@ actually says that what follows is a file name, and content of that file must be sent as payload of PUT request. Without the @, it is just a plain verbatim string that goes as payload.

**Comment by zhouyu94** [comment]
@clakech i try your way to resolve this, but shtill report 
{"error":{"root_cause":[{"type":"parse_exception","reason":"Failed to derive xcontent"}],"type":"parse_exception","reason":"Failed to derive xcontent"},"status":400}
so ,i want to consult you that es has other config?

**Comment by clakech** [comment]
@zhouyu94 your json have syntax errors ?

switch to debug in:
[ES_HOME]/config/logging.yml
change:
es.logger.level: INFO
to
es.logger.level: DEBUG
